#!/bin/bash

usr_name=$1
url="https://api.github.com/users"

col="\033[0;94m"
yell_col="\033[0;37m"
end="\033[0m"
bold="\033[1m"

if [[ -z $usr_name ]]; then
    echo "Username don't seem to be appear"
    exit 1
fi

if [[ $1 == "-rm" ]]; then
    sudo rm /usr/bin/gitfetch
    echo "Removed"
    exit 1
fi

c1="\033[7;30m  \033[0;1;30m"
c2="\033[7;31m  \033[0;1;31m"
c3="\033[7;32m  \033[0;1;32m"
c4="\033[7;33m  \033[0;1;33m"
c5="\033[7;34m  \033[0;1;34m"
c6="\033[7;35m  \033[0;1;35m"
c7="\033[7;36m  \033[0;1;36m"
c8="\033[7;37m  \033[0;1;37m"


data=$(curl -s $url/$usr_name) 


name=$( echo $data | jq -r .name)
login=$( echo $data | jq -r .login)
bio=$( echo $data | jq -r .bio | tr -d '\r\n')
follower=$( echo $data | jq -r .followers)
following=$( echo $data | jq -r .following)
profile=$( echo $data | jq -r .html_url)
repos_count=$( echo $data | jq .public_repos)
git_ver=$(git version)
hostname=$(hostname -i)
machine=$(uname -o)

clear

tput cup 1 1

url=$(echo $data | jq .avatar_url)

echo $url | xargs ascii-image-converter -C -b -c --threshold 100 -H 16 
pos=2

tput cup $((pos)) 35
printf "$col $bold OS :$yell_col $machine $end\n"
tput cup $((pos + 1)) 35
printf "$col $bold Name :$yell_col $name $end\n"
tput cup $((pos+2)) 35
printf "$col $bold Host :$yell_col $hostname $end\n"
tput cup $((pos + 3)) 35
printf "$col $bold Bio :$yell_col $bio $end\n"
tput cup $((pos + 4)) 35
printf "$col $bold Follower :$yell_col $follower $end\n"
tput cup $((pos + 5)) 35
printf "$col $bold Following :$yell_col $repos_count $end\n"
tput cup $((pos + 6)) 35
printf "$col $bold Repos :$yell_col $repos_count $end\n"
tput cup $((pos + 7)) 35
printf "$col $bold Url :$yell_col $profile $end\n"
tput cup $((pos + 8)) 35
printf "$col $bold Git Ver :$yell_col $git_ver $end\n"

tput cup 20 35
printf " $c1$c2$c3$c4$c5$c6$c7$c8\n"


